# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /bbs

spring:
  # 运行环境配置
  profiles:
    active: dev
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${faramita.datasource.url}
    username: ${faramita.datasource.username}
    password: ${faramita.datasource.password}
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  data:
    # Redis 配置
    redis:
      host: ${faramita.redis.host}
      port: ${faramita.redis.port}
      password: ${faramita.redis.password}
      database: ${faramita.redis.database}
      # 连接超时
      connect-timeout: ${faramita.redis.connect-timeout}
      # 命令执行超时
      timeout: ${faramita.redis.timeout}

      # Lettuce 配置
      lettuce:
        pool:
          max-active: ${faramita.redis.lettuce.max-active} # 最大连接数
          max-idle: ${faramita.redis.lettuce.max-idle} # 最大空闲连接
          min-idle: ${faramita.redis.lettuce.min-idle} # 最小空闲连接
          max-wait: ${faramita.redis.lettuce.max-wait} # 最大等待时间，超时报错


# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: online.faramita.bbs.entity
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名

# jwt配置
jwt: 
  secret: ${faramita.jwt.secret}
  access-token-expire: ${faramita.jwt.access-token-expire}
  refresh-token-expire: ${faramita.jwt.refresh-token-expire}

# PageHelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  default-count: true
  support-methods-arguments: true

faramita:
  # 文件存储位置
  file:
    avatar:
      root-path: ${faramita.file.avatar.root-path}
      max-size: ${faramita.file.avatar.max-size}
      expire: ${faramita.file.avatar.expire}
    image:
      max-size: ${faramita.file.image.max-size}
  # Github配置
  github:
    branch: main
    name: Nobeta
    email: 377877931@qq.com
    owner: Nobeta-Work
    repo: faramita-bbs-file
    path: img/
    token: ${faramita.github.token}


